#!/bin/bash

# Author: @vsilchuk

username=$(whoami)

echo -e "-> Start."

echo -e "\n-> Inserting module into the kernel..."
insmod src/firstmod.ko arg_username=$username

echo -e "\n-> Checking lsmod after inserting:"
lsmod | grep firstmod

echo -e "\n-> Removing from the kernel... Sleep time for 1 minute..."
rmmod firstmod 

sleep 1m

echo -e "\n-> Second inserting to the kernel..."
insmod src/firstmod.ko arg_username=$username

echo -e "\n-> Checking lsmod after inserting:"
lsmod | grep firstmod

echo -e "\n-> Second removing from the kernel..."
rmmod firstmod 

echo -e "\n-> Checking lsmod after removing:"
lsmod | grep firstmod

echo -e "\n-> Kernel log:"
dmesg -k | tail -8 

echo -e "\n-> End. See you later!"
